backend_evento_index:
    path:     /
    defaults: { _controller: "BackendBundle:Evento:index" }
    methods:  GET

backend_evento_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Evento:show" }
    methods:  GET

backend_evento_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Evento:new" }
    methods:  [GET, POST]

backend_evento_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Evento:edit" }
    methods:  [GET, POST]

backend_evento_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Evento:delete" }
    methods:  [GET]
