imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    locales_app: es|en
    locales_app_array: ['es','en']
    av.env: 'env'
#   valores identificativos de los mensajes del administrador
    av.admin.sms.id: '0'
    av.admin.sms.name: 'SMS'
#   valores identificativos de los mensajes de los usuarios desde la pagina de contacto
    av.contacto.sms.id: '1'
    av.contacto.sms.name: 'CONTACTO'
#   dirección de donde están los emails del sistema
    av.email.directory: 'CommonBundle:Email'
#   configuration files sizes
    av.max.file.size: '5' #setear en MB
    av.max.video.file.size: '120' #setear en MB

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    default_locale: '%locale%'
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection:
        enabled: false #Ver como habilitar esto y que los formularios tengan CSRF y el $form->isValid() sea = true
    validation: { enable_annotations: true }
    serializer: { enabled: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id:  ~ #Estaba así en nous_allons
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
#        handler_id: session.handler.native_file
#        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        util: '@av.util'
        uploads: 'uploads/'
        maxFileSize : '%av.max.file.size%'
        maxVideoFileSize : '%av.max.video.file.size%'
        avEnv: '%av.env%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

## Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    port:       587 # different ports are available, see SES console
    encryption: tls # TLS encryption is required
    spool:     { type: memory }

fos_rest:
    view:
        view_response_listener: 'force'
        formats:
            json: true
    format_listener:
        rules:
            - { path: ^/api, priorities: [json], fallback_format: json, prefer_extension: false }
            - { path: ^/, priorities: [ html ], fallback_format: html, prefer_extension: true }

#be_simple_i18n_routing: ~

be_simple_i18n_routing:
    locales:
        default_locale: '%locale%'
        supported: '%locales_app_array%'
        filter: true
        strict: true