_frontend_homepage:
    path:     /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: frontend_homepage }

frontend_homepage:
    path:     /{_locale}/
    defaults: { _controller: FrontendBundle:Default:index }
    defaults: { _locale: '%locale%' }
    requirements:
        _locale: '%locales_app%'

frontend_routes:
    resource: "@FrontendBundle/Resources/config/routing/frontend.yml"
    type: 'be_simple_i18n'
    prefix:   /{_locale}/
    defaults: { _locale: '%locale%'}
    requirements:
        _locale: '%locales_app%'