frontend_event_details:
    path:     /event-details/
    locales:  { es: '/evento/', en: '/event-details/' }
    defaults: { _controller: 'FrontendBundle:Default:eventDetails' }

frontend_event_details_ref:
    path:     /event-details/{ref}/
    locales:  { es: '/evento/{ref}/', en: '/event-details/{ref}/' }
    defaults: { _controller: 'FrontendBundle:Default:eventDetails' }

frontend_subscribe:
    path:     /subscribe/
    locales:  { es: '/subscribe/', en: '/subscribe/' }
    defaults: { _controller: 'FrontendBundle:Default:subscribe' }
    methods:  [POST]