backend_homepage:
    path:     /{_locale}/
    defaults: { _controller: BackendBundle:Default:index }
    requirements:
        _locale: '%locales_app%'

backend_login:
    path:     /{_locale}/login
    defaults: { _controller: BackendBundle:Security:login }
    requirements:
        _locale: '%locales_app%'

backend_logout:
    path:     /logout

bdispatch:
    path:     /dispatch/{template}
    defaults: { _controller: BackendBundle:Default:dispatch }
    options:
        expose: true

backend_configuracion:
    resource: "@BackendBundle/Resources/config/routing/configuracion.yml"
    prefix:   /{_locale}/configuracion/
    defaults: { _locale: '%locale%' }
    requirements:
        _locale: '%locales_app%'

backend_faq:
    resource: "@BackendBundle/Resources/config/routing/faq.yml"
    prefix:   /{_locale}/faq/
    defaults: { _locale: '%locale%' }
    requirements:
        _locale: '%locales_app%'

backend_newsletter:
    resource: "@BackendBundle/Resources/config/routing/newsletter.yml"
    prefix:   /{_locale}/newsletter/
    defaults: { _locale: '%locale%' }
    requirements:
        _locale: '%locales_app%'

backend_contacto:
    resource: "@BackendBundle/Resources/config/routing/contacto.yml"
    prefix:   /{_locale}/contacto/
    defaults: { _locale: '%locale%' }
    requirements:
        _locale: '%locales_app%'

backend_categoria:
    resource: "@BackendBundle/Resources/config/routing/categoria.yml"
    prefix:   /{_locale}/categoria/
    defaults: { _locale: '%locale%' }
    requirements:
        _locale: '%locales_app%'

backend_gallery_item:
    resource: "@BackendBundle/Resources/config/routing/gallery_item.yml"
    prefix:   /{_locale}/gallery-item/
    defaults: { _locale: '%locale%' }
    requirements:
        _locale: '%locales_app%'

backend_evento:
    resource: "@BackendBundle/Resources/config/routing/evento.yml"
    prefix:   /{_locale}/evento/
    defaults: { _locale: '%locale%' }
    requirements:
        _locale: '%locales_app%'
