services:
#    common.example:
#        class: BC\CommonBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    bc.util:
        class: BC\CommonBundle\Util\Util

    bc.entitysetter:
        class: BC\CommonBundle\Service\EntitySetter
        arguments: ['@service_container']

    bc.common.entity.lang.setter.listener:
        class: BC\CommonBundle\EventListener\EntityLangSetterListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    bc.common.autor.incidencia.setter.listener:
        class: BC\CommonBundle\EventListener\AutorIncidenciaSetterListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    bc.common.media.setter.listener:
        class: BC\CommonBundle\EventListener\MediaSetterListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    bc.common.translate.setter.listener:
        class: BC\CommonBundle\EventListener\TranslateSetterListener
        tags:
            - { name: doctrine.event_listener, event: postLoad }

#    bc.common.cors.listener:
#        class: BC\CommonBundle\EventListener\CorsListener
#        tags:
#           - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest , priority: 100}
#           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -100}

    bc.glr:
        class: BC\CommonBundle\Service\GenericLangRepository
        arguments: ['@doctrine.orm.entity_manager', '@service_container']

    bc.manager:
        class: BC\CommonBundle\Manager\Manager
        arguments: ['@doctrine.orm.entity_manager', '@service_container', "@twig"]

    bc.nomenclature.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\NomenclatureManager

    bc.base.api.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\BaseApiManager

    bc.cuidador.estado.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\CuidadorEstadoManager

    bc.cuidador.estado.alta.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\CuidadorEstadoAltaManager
        
    bc.mail.manager:
        class:     BC\CommonBundle\Manager\MailManager
        arguments: ["@mailer", "@twig",'@service_container']

    bc.servicio.interna.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\ServicioInternaManager

    bc.servicio.externa.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\ServicioExternaManager

    bc.servicio.housekeeping.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\ServicioHousekeepingManager

    bc.servicio.hk.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\ServicioHousekeepingManager

    bc.servicio.companionship.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\ServicioCompanionshipManager

    bc.servicio.cs.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\ServicioCompanionshipManager

    bc.servicio.personal.care.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\ServicioPersonalCareManager

    bc.servicio.pc.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\ServicioPersonalCareManager

    bc.servicio.living.in.care.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\ServicioLivingInCareManager

    bc.servicio.lc.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\ServicioLivingInCareManager

    bc.incidencia.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\IncidenciaManager

    bc.incidencia.estado.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\IncidenciaEstadoManager
        
    bc.pss.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\ProtocoloSocioSanitarioManager

    bc.tipo.cuidador.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\TipoCuidadorManager

    bc.entrevista.estado.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\EntrevistaEstadoManager

    bc.cupon.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\CuponManager

    bc.servicio.estado.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\ServicioEstadoManager

    bc.compra.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\CompraManager

    bc.horario.entrevista.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\HorarioEntrevistaManager

    bc.provincia.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\ProvinciaManager

    bc.pais.manager:
        parent: bc.manager
        class: BC\CommonBundle\Manager\PaisManager